#!/usr/bin/env python
# -*- mode: python -*-

"""
List projects.
"""

# You need to run this program with all the scipion env variables defined.
# (For example, with "scipion run sci-proj".)

from argparse import ArgumentParser

from pyworkflow.manager import Manager


def main():
   parser = ArgumentParser(description=__doc__)
   parser.add_argument('--path', action='store_true', help='show project path')
   args = parser.parse_args()

   manager = Manager()
   for p_info in manager.listProjects():
      extra = ''
      if args.path:
         proj = manager.loadProject(p_info.projName)
         extra += ' (%s)' % proj.path
      print '%s%s' % (p_info.projName, extra)


if __name__ == '__main__':
   main()
